name: simple_news
description: A simple news application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+4
  firebase_auth: ^0.14.0+5
  http: ^0.12.0+2
  url_launcher: ^5.1.2
  image_picker: ^0.6.1+4
  connectivity: ^0.4.4
  firebase_storage: ^3.0.6
  flutter_swiper: ^1.1.6
  google_sign_in: ^4.0.7
  provider: ^3.1.0
  email_validator: ^1.0.0
  flushbar: ^1.9.0
  flutter_spinkit: ^3.1.0
  auto_size_text: ^2.1.0
  simple_animations: ^1.3.3
  shimmer: ^1.0.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/bg_placeholder.jpeg
    - assets/placeholder.png
  